server:
  port: 8080
spring:
  application:
    name: cadastro-service
#  security:
#    user:
#      name: test
#      password: test
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: ${logging_level:INFO}
  config: