server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /api

spring:
  application:
    name: cadastro-service
  datasource:
    url: jdbc:h2:mem:cadastrodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
logging:
  level:
    root: INFO