server:
  port: 8080
spring:
  application:
    name: cadastro-service
  datasource:
    url: jdbc:h2:mem:cadastrodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: INFO
  config: